//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainSoftLib.MathExpressions.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainSoftLib.MathExpressions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The IExpression.Evaluate property can not be null..
        /// </summary>
        internal static string EvaluatePropertyCanNotBeNull {
            get {
                return ResourceManager.GetString("EvaluatePropertyCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The function name &apos;{0}&apos; is already registered..
        /// </summary>
        internal static string FunctionNameRegistered {
            get {
                return ResourceManager.GetString("FunctionNameRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid number of arguments: .
        /// </summary>
        internal static string InvalidArgumentCount {
            get {
                return ResourceManager.GetString("InvalidArgumentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid character: .
        /// </summary>
        internal static string InvalidCharacterEncountered {
            get {
                return ResourceManager.GetString("InvalidCharacterEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid convertion expression: .
        /// </summary>
        internal static string InvalidConvertionExpression {
            get {
                return ResourceManager.GetString("InvalidConvertionExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid function name &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidFunctionName {
            get {
                return ResourceManager.GetString("InvalidFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid length of array..
        /// </summary>
        internal static string InvalidLengthOfArray {
            get {
                return ResourceManager.GetString("InvalidLengthOfArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid math expression..
        /// </summary>
        internal static string InvalidMathExpression {
            get {
                return ResourceManager.GetString("InvalidMathExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid number format: .
        /// </summary>
        internal static string InvalidNumberFormat {
            get {
                return ResourceManager.GetString("InvalidNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid operator: .
        /// </summary>
        internal static string InvalidOperator {
            get {
                return ResourceManager.GetString("InvalidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid symbol on stack: .
        /// </summary>
        internal static string InvalidSymbolOnStack {
            get {
                return ResourceManager.GetString("InvalidSymbolOnStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid function or variable: .
        /// </summary>
        internal static string InvalidVariableEncountered {
            get {
                return ResourceManager.GetString("InvalidVariableEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid number for expression: .
        /// </summary>
        internal static string NotEnoughNumbers {
            get {
                return ResourceManager.GetString("NotEnoughNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unbalanced parentheses..
        /// </summary>
        internal static string UnbalancedParentheses {
            get {
                return ResourceManager.GetString("UnbalancedParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The variable name conflicts with function &apos;{0}&apos;..
        /// </summary>
        internal static string VariableNameConflict {
            get {
                return ResourceManager.GetString("VariableNameConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The variable name can only contain letters..
        /// </summary>
        internal static string VariableNameContainsLetters {
            get {
                return ResourceManager.GetString("VariableNameContainsLetters", resourceCulture);
            }
        }
    }
}
